### ISSUE TITLE
[Primary Feature] Authentication

### ISSUE THREAD

**Issue by tapatiohaxx** [BroncoDirectMe/Backend#24]
<h1> User Story </h1>
<H2> <b> Description </b> </h2>
<p> As a developer, I want to ensure that users are authenticated within the application so that professor rating is not skewed by mass voting or other means. </p> 

<h2> <b> Technical Task </b> </h2>
<ul>
<li> Utilize Microsoft OAuth library to login a user</li>
<li> Return an access token associated with a user login that has to be passed into the backend. </li>
</ul>

<h2> <b> Acceptance Criteria </b> </h2>

- Users can login in with their MS Accounts
- MS Accounts not affiliated with CPP cannot use the application
- Users cannot vote on a professor more than once, unless it differs from their previous vote.

**Comment by misslame** [comment]
@GuyWhoCode  and @ZombiMigz  please link the PR to the issue
