### ISSUE TITLE
[Primary Feature] Make Endpoints for Upvoting and Downvoing.

### ISSUE THREAD

**Issue by tapatiohaxx** [BroncoDirectMe/Backend#26]
### User Story
As a developer, I want a convenient way to track the students' feedback towards the professors in the database.  

### Technical Tasks
- Make sure the API can have endpoints that can send upvotes and downloads to the database.

### Acceptance Criteria
- The database can accept upvotes and downvotes.

**Comment by misslame** [comment]
This will need further discussion: 

We need a way to track upvotes/downvotes and display them. Front end + Back end communication.

**Comment by TonyTong112358** [comment]
This should also have been closed my bad
