### ISSUE TITLE
[PRIMARY FEATURE] Testing API Endpoints

### ISSUE THREAD

**Issue by ZombiMigz** [BroncoDirectMe/Backend#29]
### User Story
As a developer I want the REST API endpoints tested so I know they are returning the correct data.

### Technical Task
- Research testing and implement testing
- Add testing command to npm

### Acceptance Criteria
- Running `npm run test` tests the endpoints and properly identifies errors

**Comment by misslame** [comment]
@E-A-H62  and @peppacaiou  please link the PR to the issue

**Comment by TonyTong112358** [comment]
This should have been close my bad.
