### ISSUE TITLE
[SECONDARY FEATURE] Scrape Course Catalog for Pre-reqs

### ISSUE THREAD

**Issue by U-k-t** [BroncoDirectMe/Backend#39]
One-time task

### User Story
As a developer, I should be able to access course details so that I can query key characteristics about courses. 

### Technical Task:
Scrape the current CPP course catalog for course numbers, pre-requisites, course categories + GE areas
You may want to use the helper functions implemented in [Backend#58 Curriculum Table Helper Functions](https://github.com/BroncoDirectMe/Backend/issues/58)
### Acceptance Criteria:
- Populated database table mapping course numbers with their details, specifically pre-reqs of courses.

### Related Issues: 
- [Frontend#52 Search-Level Course Category](https://github.com/BroncoDirectMe/Frontend/issues/52)
- [Backend#58 Curriculum Table Helper Functions](https://github.com/BroncoDirectMe/Backend/issues/58)

**Comment by GuyWhoCode** [comment]
Combined with https://github.com/BroncoDirectMe/Backend/issues/43
