### ISSUE TITLE
[SECONDARY FEATURE] Scrape Curriculum Requirements

### ISSUE THREAD

**Issue by U-k-t** [BroncoDirectMe/Backend#43]
One-time task

### User Story
As a developer, I want to document the past five (5) years of curriculum requirements for each major to reference the majority of students' degree requirements

### Technical Task:
Scrape the CPP course catalog for the past 5 years of Major Program requirements

### Acceptance Criteria:
- Populated database table mapping course numbers with their details

### Related Issues: 
- [Frontend#52 Search-Level Course Category](https://github.com/BroncoDirectMe/Frontend/issues/52)

**Comment by GuyWhoCode** [comment]
Combined with another issue.
