### ISSUE TITLE
[PRIMARY FEATURE] MySQL Client

### ISSUE THREAD

**Issue by ZombiMigz** [BroncoDirectMe/Backend#6]
### User Story
As a developer, I want easy ways for me to modify the database so I don't have to worry too much about SQL syntax.

### Technical Tasks:
- install mysql client (https://www.npmjs.com/package/mysql2) (we're going to be writing raw sql for practice 😋)
- Setup mysql client (use environmental variables and dot-env npm package)
- Design mysql schema with a professor table. Each professor has the following fields: BroncoDirect Name, RMP Name, RMP URL, Rating, Difficulty, TakeAgain(float), we might have more later on. Primary Key should be the BroncoDirect Name. All other values are nullable. 
- Design functions to add/update a professor and find a professor based on BroncoDirect Name.
- MAKE SURE THIS IS ALL WELL DOCUMENTED

### Acceptance Criteria:
- Functions exist to add and update a professor in a mysql database
- Schema, function usage, environmental variables, etc. are all well documented

**Comment by GuyWhoCode** [comment]
Merged into dev and main branch.
