### ISSUE TITLE
[PRIMARY FEATURE] Professor Search Endpoints

### ISSUE THREAD

**Issue by ZombiMigz** [BroncoDirectMe/Backend#7]
### User Story
As a developer I want easy to use REST API endpoints so I can interact with the backend.

### Technical Tasks:
- For all of these use dummy data, temporary schema can be found in #6, but you don't have to follow it. We just want to know the endpoints work.
- POST endpoint that takes an input string and returns a list of professors with names similar to the string. Don't implement the logic to find similarity, just return a random list. This will be implemented on the mysql side.
- POST endpoint that takes a professor name and returns only one result. If the professor name is not found, return an error.
- Code should start in server.ts and run on `npm run api`

### Acceptance Criteria:
- sending string to /search endpoint returns random list of professors
- sending string to /professor API returns single professor data or null if doesn't exist

**Comment by misslame** [comment]
May require a connection story/update story for sprint 2 to ensure connection between work.
